import axios from 'axios';

const api = axios.create({
    baseURL: "http://localhost:3000",
    withCredentials: true
})

/**
 * This is the function to generate the interview report by ai.
 * @param {jobDescription, selfDescription, resumeFile} param0 
 * @returns The interview Report generated by ai
 */
export async function generateInterviewReport({ jobDescription, selfDescription, resumeFile }) {
    try {
        const formData = new FormData();
        formData.append("jobDescription", jobDescription);
        formData.append("selfDescription", selfDescription);
        formData.append("resume", resumeFile);

        const response = await api.post('/api/report/generate', formData, {
            headers: {
                "Content-Type": "multipart/form-data"
            }
        })

        return response.data

    } catch (error) {
        const message = error.response?.data?.message || "Something went wrong";
        throw new Error(message);
    }
}



/**
 * This function is to get the interview report by an interview ID
 * @returns The interview Report generated by ai
 */
export async function fetchReportById(interviewId) {
    try {
        const response = await api.get(`/api/report/${interviewId}`);

        return response.data

    } catch (error) {
        const message = error.response?.data?.message || "Something went wrong";
        throw new Error(message);
    }

}


/**
 * This function is to fetch all the interview report of the logged in user. 
 * @returns The interview Reports for the loggedin user
 */
export async function fetchAllReports() {
    try {
        const response = await api.get('/api/report/fetchAllReports');
        return response.data;
    } catch (error) {
        const message = error.response?.data?.message || "Something went wrong";
        throw new Error(message);
    }
}


export async function generatePdf({interviewReportId}) {
    try {
        const response = await api.post(`/api/report/resume/pdf/${interviewReportId}`, null, {
            responseType: 'blob'
        })
        return response.data;

    } catch (error) {
        const message = error.response?.data?.message || "Something went wrong";
        throw new Error(message);
    }
}

